server:
  port: 3004
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default:zone: "http://localhost:8761/eureka/"
      instance: localhost
spring:
  application:
    name: SECURITY-SERVICE